language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    recipients:
      - congrui-yi@uiowa.edu
    on_success: change
    on_failure: change
